id: IC7B810D1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-24T23:17:52+00:00'
last_modified: '2022-06-08T03:27:00.856333+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG6124
  title: འཛམ་གླིང་ཉེ་རབས་ལོ་རྒྱུས་ཀྱི་གཏམ་རྒྱུད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '7886':
      image_group_id: I1KG8447
      title: ''
      total_pages: 426
      order: 1
      base_file: 7886.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
